### ISSUE TITLE
All examples fail on initial reset

### ISSUE THREAD

**Issue by ahalwright** [projectmesa/mesa-examples#1]
All of the examples are failing to run with the same error message.

I am running in Python 3.5.2 IDLE on Windows.

For example, I open the file Flockers\Flocker_Server.py and try to run it.  Here is the error message:
Interface starting at http://127.0.0.1:8888
Socket opened!
{"type":"reset"}
ERROR:tornado.application:Future <tornado.concurrent.Future object at 0x039CF070> exception was never retrieved: Traceback (most recent call last):
  File "C:\Users\alden.wright\AppData\Local\Programs\Python\Python35-32\lib\site-packages\tornado\gen.py", line 285, in wrapper
    yielded = next(result)
  File "C:\Users\alden.wright\AppData\Local\Programs\Python\Python35-32\lib\site-packages\mesa\visualization\ModularVisualization.py", line 272, in run_model
    self.model.step()
  File "C:\Users\Public\mesa\mesa-examples\examples\Flockers\flockers.py", line 149, in step
    self.schedule.step()
  File "C:\Users\alden.wright\AppData\Local\Programs\Python\Python35-32\lib\site-packages\mesa\time.py", line 102, in step
    agent.step()
TypeError: step() missing 1 required positional argument: 'model'

============================
The  mesa-schelling-example  runs correctly.

Am I doing something wrong?

**Comment by jackiekazil** [comment]
Hello! This is a future home of examples. They now exist in the main repo here: https://github.com/projectmesa/mesa/tree/master/examples

We are going to try to move them here, but this is not stable / up to date. I updated the description to reflect this until we are ready to commit to this. 

When you clone the other repo and try to run those examples, let me know if you have any issues.
